-   id: import_rules_enforcer
    name: ImportRulesEnforcer
    description: Converts absolute imports to relative if modules have the same parent and relative to absolute if importing from parent of the parent. Replaces import from __all__ if dirrect import is possible
    entry: import_rules_enforcer
    language: python
    types: [python]
    files: ''
