permissions:
  contents: write

jobs:
  bump_and_tag:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' ||
        (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: pip install poetry
        name: Install Poetry

      - name: Bump pyproject.toml version
        run: |
          poetry version patch
          git config user.name "github-actions[bot]"
          git config user.email "[email protected]"
          git add pyproject.toml
          git commit -m "bump: patch version"

      - id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          release_branches: main

      - name: Push bump commit
        run: git push origin main

      - name: Push tag
        run: git push origin ${{ steps.tag.outputs.new_tag }}
