name: Bump and Tag Version on Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  bump_and_tag:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
        fetch-depth: 0

      - name: Set up Python & bump version
        run: |
          pip install poetry
          poetry version patch
          git commit -am "bump: patch version"

      - name: Push bump commit
        run: git push origin main

      - name: Tag automatically
        uses: mathieudutour/github-tag-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          BUMP: patch
