name: Bump and Tag Version on Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  bump_and_tag:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump patch version and commit
        run: |
          pip install poetry
          poetry version patch
          git config user.name "github-actions[bot]"
          git config user.email "[email protected]"
          git add pyproject.toml
          git commit -m "bump: patch version"

      - name: Tag automatically
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          release_branches: main

